# Generated by Django 5.2.4 on 2025-07-05 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('type', models.CharField(max_length=100, verbose_name='Typ')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numer seryjny')),
                ('purchase_date', models.DateField(verbose_name='Data zakupu')),
                ('location', models.CharField(max_length=100, verbose_name='Lokalizacja')),
                ('status', models.CharField(choices=[('available', 'Dostępny'), ('in_use', 'W użyciu'), ('service', 'Serwis'), ('retired', 'Wycofany')], default='available', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Przypisany użytkownik')),
            ],
            options={
                'verbose_name': 'Sprzęt',
                'verbose_name_plural': 'Sprzęt',
                'ordering': ['-created_at'],
            },
        ),
    ]
