# Generated by Django 5.2.4 on 2025-07-05 00:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Przypisany użytkownik'),
        ),
        migrations.CreateModel(
            name='EquipmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data przekazania')),
                ('reason', models.TextField(blank=True, verbose_name='Powód przekazania')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='equipment.equipment', verbose_name='Sprzęt')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='Od użytkownika')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='Do użytkownika')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='Przekazane przez')),
            ],
            options={
                'verbose_name': 'Przekazanie sprzętu',
                'verbose_name_plural': 'Przekazania sprzętu',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
