# Generated by Django 5.2.6 on 2025-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_assigned_to_equipmenttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer faktury'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena zakupu'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dostawca'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Koniec gwarancji'),
        ),
    ]
