# Generated by Django 5.2.6 on 2025-09-22 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_invoice_number_equipment_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Przegląd prewencyjny'), ('repair', 'Naprawa'), ('cleaning', 'Czyszczenie'), ('update', 'Aktualizacja'), ('inspection', 'Kontrola')], max_length=20, verbose_name='Typ konserwacji')),
                ('scheduled_date', models.DateField(verbose_name='Zaplanowana data')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Data wykonania')),
                ('description', models.TextField(verbose_name='Opis konserwacji')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='Technik')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Wykonane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Sprzęt')),
            ],
            options={
                'verbose_name': 'Harmonogram konserwacji',
                'verbose_name_plural': 'Harmonogramy konserwacji',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
