# Generated by Django 5.2.6 on 2025-09-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_maintenanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Kod QR'),
        ),
    ]
