# Generated by Django 5.2.6 on 2025-09-30 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttransfer',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Oczekuje na akceptację'), ('approved', 'Zaakceptowane'), ('rejected', 'Odrzucone'), ('cancelled', 'Anulowane')], default='pending', max_length=20, verbose_name='Status akceptacji'),
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data akceptacji'),
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL, verbose_name='Zaakceptowane przez'),
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Powód odrzucenia'),
        ),
    ]
